### ISSUE TITLE
All-pass configuration output does not match input

### ISSUE THREAD

**Issue by LBeaufore** [pueo-pynq/pueo-pynq-designs#1]
*EDITED TO REMOVE INCORRECT PLOTS, SEE BELOW*

**Comment by LBeaufore** [comment]
I believe this is a processing error on my end now, not a firmware issue. Will reopen if that's not the case.

**Comment by LBeaufore** [comment]
I believe this is a processing error on my end now, not a firmware issue. Will reopen if that's not the case.

**Comment by LBeaufore** [comment]
The plots above show time-aligned data in and out of the Zero FIR.  Channels 0 and 1 were fed from two ends of a tee from the same function generator. Naively, we would expect the input and output of these two signals to be identical when correctly aligned in time, and therefore have deltas of 0. Only the first two samples of each group of 8 will have output, so the delta values are decimated to only reflect those two channels (in orange). 


![Channel0](https://github.com/pueo-pynq/pueo-pynq-designs/assets/566570/64c5b43e-6aeb-4797-a588-5cd32fe495b7)
![Channel1](https://github.com/pueo-pynq/pueo-pynq-designs/assets/566570/5abe6834-18ff-472a-9299-0bb6da20ee68)
![Channel0_deltas](https://github.com/pueo-pynq/pueo-pynq-designs/assets/566570/89d77229-c55e-4ef8-b6c4-45dacb98fa61)
![Channel1_deltas](https://github.com/pueo-pynq/pueo-pynq-designs/assets/566570/2d001a6a-f1aa-4fd5-86c0-0271d430fa07)

Here is the biquad configuration
```
total = 32768
# A = int(0.35*total)
# B = total - 2*A
B=total
A=0
if(2*A+B != total):
    raise Exception("Coefficients don't sum: %s"%(2*A+B))
offset = 0x0
# Single Zero FIR coefficients
zcu.wbw(offset+0x04, B)
zcu.wbw(offset+0x04, A)

# Pole IIR coefficients
zcu.wbw(offset+0x08, 0)
zcu.wbw(offset+0x08, 0)
zcu.wbw(offset+0x08, 0)
zcu.wbw(offset+0x08, 0)

# Incremental computation coefficients
zcu.wbw(offset+0x0C, 0)
zcu.wbw(offset+0x0C, 0)

# f FIR coefficients
zcu.wbw(offset+0x10, 0) #D_FF
zcu.wbw(offset+0x10, 0) #X6
zcu.wbw(offset+0x10, 0)
zcu.wbw(offset+0x10, 0)
zcu.wbw(offset+0x10, 0)
zcu.wbw(offset+0x10, 0)
zcu.wbw(offset+0x10, 0)

# g FIR coefficients
zcu.wbw(offset+0x14, 0) #E_GG
zcu.wbw(offset+0x14, 0) #X7
zcu.wbw(offset+0x14, 0)
zcu.wbw(offset+0x14, 0)
zcu.wbw(offset+0x14, 0)
zcu.wbw(offset+0x14, 0)
zcu.wbw(offset+0x14, 0)
zcu.wbw(offset+0x14, 0)

# g coefficient in F
zcu.wbw(offset+0x18, 0) #D_FG

# f coefficient in G
zcu.wbw(offset+0x1C, 0) #E_GF

zcu.wbw(offset+0x00, 1)



offset = 0x80
# Single Zero FIR coefficients
zcu.wbw(offset+0x04, B)
zcu.wbw(offset+0x04, A)

# Pole IIR coefficients
zcu.wbw(offset+0x08, 0)
zcu.wbw(offset+0x08, 0)
zcu.wbw(offset+0x08, 0)
zcu.wbw(offset+0x08, 0)

# Incremental computation coefficients
zcu.wbw(offset+0x0C, 0)
zcu.wbw(offset+0x0C, 0)

# f FIR coefficients
zcu.wbw(offset+0x10, 0) #D_FF
zcu.wbw(offset+0x10, 0) #X6
zcu.wbw(offset+0x10, 0)
zcu.wbw(offset+0x10, 0)
zcu.wbw(offset+0x10, 0)
zcu.wbw(offset+0x10, 0)
zcu.wbw(offset+0x10, 0)

# g FIR coefficients
zcu.wbw(offset+0x14, 0) #E_GG
zcu.wbw(offset+0x14, 0) #X7
zcu.wbw(offset+0x14, 0)
zcu.wbw(offset+0x14, 0)
zcu.wbw(offset+0x14, 0)
zcu.wbw(offset+0x14, 0)
zcu.wbw(offset+0x14, 0)
zcu.wbw(offset+0x14, 0)

# g coefficient in F
zcu.wbw(offset+0x18, 0) #D_FG

# f coefficient in G
zcu.wbw(offset+0x1C, 0) #E_GF

zcu.wbw(offset+0x00, 1)
```

**Comment by LBeaufore** [comment]
![Channel0_raw](https://github.com/pueo-pynq/pueo-pynq-designs/assets/566570/37c54962-b02a-4a2d-9e56-6eb8eacdd6b8)
![Channel1_raw](https://github.com/pueo-pynq/pueo-pynq-designs/assets/566570/cd80c181-91fc-4ac8-acf8-a37b90b20876)

The plots above show time-aligned data in and out of the Zero FIR.  Channels 0 and 1 were fed from two ends of a tee from the same function generator. Naively, we would expect the input and output of these two signals to be identical when correctly aligned in time, and therefore have deltas of 0. The plots below show the difference (deltas) of the output from the input. Only the first two samples of each group of 8 will have output, so the delta values are decimated to only reflect those two channels (in orange). 


![Channel0](https://github.com/pueo-pynq/pueo-pynq-designs/assets/566570/f3320844-333a-429c-a774-81dde53b3c3c)
![Channel1](https://github.com/pueo-pynq/pueo-pynq-designs/assets/566570/690c6176-4418-4a27-b667-5ff42ab9c4f8)
![Channel0_deltas](https://github.com/pueo-pynq/pueo-pynq-designs/assets/566570/02925883-ac87-43a1-a558-70e3595fd73f)
![Channel1_deltas](https://github.com/pueo-pynq/pueo-pynq-designs/assets/566570/b4a45ce6-b102-47b2-a557-870e803c6561)


Here is the biquad configuration
```
total = 32768
# A = int(0.35*total)
# B = total - 2*A
B=total
A=0
if(2*A+B != total):
    raise Exception("Coefficients don't sum: %s"%(2*A+B))
offset = 0x0
# Single Zero FIR coefficients
zcu.wbw(offset+0x04, B)
zcu.wbw(offset+0x04, A)

# Pole IIR coefficients
zcu.wbw(offset+0x08, 0)
zcu.wbw(offset+0x08, 0)
zcu.wbw(offset+0x08, 0)
zcu.wbw(offset+0x08, 0)

# Incremental computation coefficients
zcu.wbw(offset+0x0C, 0)
zcu.wbw(offset+0x0C, 0)

# f FIR coefficients
zcu.wbw(offset+0x10, 0) #D_FF
zcu.wbw(offset+0x10, 0) #X6
zcu.wbw(offset+0x10, 0)
zcu.wbw(offset+0x10, 0)
zcu.wbw(offset+0x10, 0)
zcu.wbw(offset+0x10, 0)
zcu.wbw(offset+0x10, 0)

# g FIR coefficients
zcu.wbw(offset+0x14, 0) #E_GG
zcu.wbw(offset+0x14, 0) #X7
zcu.wbw(offset+0x14, 0)
zcu.wbw(offset+0x14, 0)
zcu.wbw(offset+0x14, 0)
zcu.wbw(offset+0x14, 0)
zcu.wbw(offset+0x14, 0)
zcu.wbw(offset+0x14, 0)

# g coefficient in F
zcu.wbw(offset+0x18, 0) #D_FG

# f coefficient in G
zcu.wbw(offset+0x1C, 0) #E_GF

zcu.wbw(offset+0x00, 1)



offset = 0x80
# Single Zero FIR coefficients
zcu.wbw(offset+0x04, B)
zcu.wbw(offset+0x04, A)

# Pole IIR coefficients
zcu.wbw(offset+0x08, 0)
zcu.wbw(offset+0x08, 0)
zcu.wbw(offset+0x08, 0)
zcu.wbw(offset+0x08, 0)

# Incremental computation coefficients
zcu.wbw(offset+0x0C, 0)
zcu.wbw(offset+0x0C, 0)

# f FIR coefficients
zcu.wbw(offset+0x10, 0) #D_FF
zcu.wbw(offset+0x10, 0) #X6
zcu.wbw(offset+0x10, 0)
zcu.wbw(offset+0x10, 0)
zcu.wbw(offset+0x10, 0)
zcu.wbw(offset+0x10, 0)
zcu.wbw(offset+0x10, 0)

# g FIR coefficients
zcu.wbw(offset+0x14, 0) #E_GG
zcu.wbw(offset+0x14, 0) #X7
zcu.wbw(offset+0x14, 0)
zcu.wbw(offset+0x14, 0)
zcu.wbw(offset+0x14, 0)
zcu.wbw(offset+0x14, 0)
zcu.wbw(offset+0x14, 0)
zcu.wbw(offset+0x14, 0)

# g coefficient in F
zcu.wbw(offset+0x18, 0) #D_FG

# f coefficient in G
zcu.wbw(offset+0x1C, 0) #E_GF

zcu.wbw(offset+0x00, 1)
```

**Comment by LBeaufore** [comment]
Same issue if the gain in the filter is set to 1 (total = B = 16384). The plots below no longer have a /2 correction factor.
![Channel0_deltas_gain1](https://github.com/pueo-pynq/pueo-pynq-designs/assets/566570/082e328a-552a-4a43-852d-a68871397428)
![Channel1_deltas_gain1](https://github.com/pueo-pynq/pueo-pynq-designs/assets/566570/a4abb73d-90a7-4ca8-a42b-1aa651ca2603)

**Comment by barawn** [comment]
Oh, this might be an analysis thing. The raw gated data is just the input data directly, so it's still 16 bits, and it's still got those unused bottom 4 bits.

But when it passes to the biquad, those bottom 4 bits are dropped (via the unpack function), since the biquad is just 12 bits.

Then when it comes out of the biquad, it's still 12 bits, but it's repacked into 16 bits (using the pack function). So when you do the difference, any time those bottom 4 bits are nonzero, you'll get a difference. Hence the reason that all of the differences are bounded by +16/-16.

**Comment by LBeaufore** [comment]
Just to document what I said in person here - yeah this explanation matches with what I was suspecting. What I'm still checking on is why it goes all the way to a difference of 16, and not 15 as I would expect from truncation. Here's the result if I divide the original values by 2^4 and then re-extend in Python:

![Untitled](https://github.com/pueo-pynq/pueo-pynq-designs/assets/566570/e61d49ae-2a6b-4b40-9e2c-a2fbcbf50ce8)
![Untitled2](https://github.com/pueo-pynq/pueo-pynq-designs/assets/566570/2d591842-eb73-45a6-be34-b026445efb65)

**Comment by cozzyd** [comment]
4 bits has a range of -16 to 15, no?

**Comment by LBeaufore** [comment]
Was an issue with how I was truncating out the twos complement negative values in python. Fixed now!

![Untitled](https://github.com/pueo-pynq/pueo-pynq-designs/assets/566570/4a90419b-51f7-4bb9-95e2-72b286c0922e)
![Untitled2](https://github.com/pueo-pynq/pueo-pynq-designs/assets/566570/95b4ed28-7720-4a19-8de6-2f99c37685b6)
